language: python
matrix:
  include:
    # works on Precise and Trusty
    - os: linux
      python:
        - "2.7"
        - "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env:
         - CC=gcc-4.9
         - CXX=g++-4.9"

    # works on Precise and Trusty
    - os: linux
      python:
        - "2.7"
        - "3.6"
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
         - CC=gcc-5
         - CXX=g++-5"
# command to install dependencies
before_install:
    - eval "${MATRIX_EVAL}"
install:
  - pip install --upgrade pip
  - pip install -r requirements.txt
  - python setup.py install
# tests
script:
  - cd tests
  - python -m unittest discover -p '*.py'
