language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install --progress-bar off -r requirements.txt
  - python setup.py install
# tests
script:
  - cd tests
  - python -m unittest discover -p '*.py'
